//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColegioAmericano.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ColegioEntities : DbContext
    {
        public ColegioEntities()
            : base("name=ColegioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cargo> Cargo { get; set; }
        public virtual DbSet<Curso> Curso { get; set; }
        public virtual DbSet<Dia> Dia { get; set; }
        public virtual DbSet<egresos> egresos { get; set; }
        public virtual DbSet<Estudiante> Estudiante { get; set; }
        public virtual DbSet<Gasto> Gasto { get; set; }
        public virtual DbSet<Grado> Grado { get; set; }
        public virtual DbSet<ingreso> ingreso { get; set; }
        public virtual DbSet<Inscripcion> Inscripcion { get; set; }
        public virtual DbSet<Mes> Mes { get; set; }
        public virtual DbSet<Pago_salario> Pago_salario { get; set; }
        public virtual DbSet<Pagos> Pagos { get; set; }
        public virtual DbSet<Periodo> Periodo { get; set; }
        public virtual DbSet<Profesores> Profesores { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
