//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColegioAmericano.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class egresos
    {
        public int Id { get; set; }
        public Nullable<int> gasto_id { get; set; }
        public Nullable<int> pago_id { get; set; }
    
        public virtual Gasto Gasto { get; set; }
        public virtual Pago_salario Pago_salario { get; set; }
    }
}
