//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColegioAmericano.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Periodo
    {
        public int Id { get; set; }
        public Nullable<int> Profesor_id { get; set; }
        public Nullable<int> Curso_id { get; set; }
        public Nullable<int> Dia_id { get; set; }
        public Nullable<System.TimeSpan> Hora_inicio { get; set; }
        public Nullable<System.TimeSpan> Hora_final { get; set; }
    
        public virtual Curso Curso { get; set; }
        public virtual Dia Dia { get; set; }
        public virtual Profesores Profesores { get; set; }
    }
}
